theme: minima
author: Simon Lelorrain

title: '101010'
description: 'Another useless weblog.'

twitter_username: D3C4P5
github_username: slelorrain
rss: RSS

show_excerpts: true

plugins:
- jekyll-feed
- jekyll-seo-tag
